### PR TITLE
Compatibility with ghc-8.2

### LINKED ISSUE #1: deriving Typeable1 not working with GHC8.2 / duplicate derivation
a straightforward `cabal install` of the current master branch gives the following error with GHC 8.2.1:
```
[1 of 1] Compiling Network.IP.Addr  ( src/Network/IP/Addr.hs, dist/build/Network/IP/Addr.o )

src/Network/IP/Addr.hs:566:19: error:
    • Illegal instance for a type synonym
      A class instance must be for a class
    • In the stand-alone deriving instance for ‘Typeable1 InetAddr’
    |
566 | deriving instance Typeable1 InetAddr
    |                   ^^^^^^^^^^^^^^^^^^

src/Network/IP/Addr.hs:852:19: error:
    • Illegal instance for a type synonym
      A class instance must be for a class
    • In the stand-alone deriving instance for ‘Typeable1 InetAddr’
    |
852 | deriving instance Typeable1 InetAddr
    |                   ^^^^^^^^^^^^^^^^^^
```

Also: note that the instance derivation for `InetAddr` appears twice in the source file. Did you by any chance mean to derive for `NetAddr` in line 566?

Maybe the GHC 8.2 migration guide sheds some light on the changes involving `Typeable1`?
[https://ghc.haskell.org/trac/ghc/wiki/Migration/8.2](url)

### PR DESCRIPTION
**Pull request by alexbiehl**
Fixes #1 .

### CODE REVIEW

**Comment by mvv** [comment]
Thanks
